const MASA_APPS={dex:'http://127.0.0.1:5502/masa_dex',miner:'http://127.0.0.1:8080/'};
const modal=document.getElementById('modal'), modalCard=document.getElementById('modalCard'), toast=document.getElementById('toast');
const address=document.getElementById('address');
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function openModal(html){modalCard.innerHTML=html;modal.classList.add('show')}
function closeModal(){modal.classList.remove('show');modalCard.innerHTML=''}
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
document.getElementById('copyAddress').onclick=async()=>{try{await navigator.clipboard.writeText(address.textContent.trim());showToast('Wallet address copied')}catch{showToast('Copy unavailable in this browser')}};
document.getElementById('toggleBalance').onclick=()=>{const b=document.getElementById('balance');b.textContent=b.textContent==='••••••'?'12,482.51':'••••••';document.getElementById('fiat').textContent=b.textContent==='••••••'?'••••••':'≈ Rp 220,000,000'};
function openExternal(url,name){showToast('Opening '+name+'…');setTimeout(()=>window.location.href=url,180)}
document.getElementById('tradeBtn').onclick=()=>openExternal(MASA_APPS.dex,'MASA DEX');
document.getElementById('minerBtn').onclick=()=>openExternal(MASA_APPS.miner,'MASA Miner');
document.getElementById('tradeCard').onclick=()=>openExternal(MASA_APPS.dex,'MASA DEX');
document.getElementById('minerCard').onclick=()=>openExternal(MASA_APPS.miner,'MASA Miner');
function sendScreen(){openModal(`<div class="modal-head"><h3>Send MASA</h3><button class="close" onclick="closeModal()">×</button></div><div class="field"><label>RECIPIENT</label><input placeholder="MASA address"></div><div class="field"><label>AMOUNT</label><input type="number" placeholder="0.00"></div><div class="field"><label>NETWORK FEE</label><div style="padding:14px;background:#090909;border:1px solid rgba(255,255,255,.08);border-radius:12px">0.12 MASA <span style="float:right;color:#8f8b82">Transparent</span></div></div><div class="modal-actions"><button onclick="closeModal()">Cancel</button><button class="gold" onclick="showToast('Review transaction next');">Continue</button></div>`)}
function receiveScreen(){openModal(`<div class="modal-head"><h3>Receive MASA</h3><button class="close" onclick="closeModal()">×</button></div><div class="qr-box"><div class="qr"></div></div><div style="font-family:ui-monospace;font-size:12px;color:#cfc9bd;text-align:center;word-break:break-all">${address.textContent}</div><div class="modal-actions" style="margin-top:18px"><button onclick="navigator.clipboard?.writeText('${address.textContent}');showToast('Address copied')">Copy</button><button class="gold" onclick="showToast('Share sheet unavailable in demo')">Share</button></div>`)}
function scanScreen(){openModal(`<div class="modal-head"><h3>Scan MASA QR</h3><button class="close" onclick="closeModal()">×</button></div><div style="height:300px;border:1px solid var(--line);border-radius:18px;background:radial-gradient(circle,rgba(217,170,74,.12),#080808);display:grid;place-items:center;margin:20px 0"><div style="width:210px;height:210px;border:2px solid #f5f0e5;border-radius:22px;box-shadow:0 0 35px rgba(217,170,74,.14);display:grid;place-items:center;color:var(--gold2);font-size:12px;letter-spacing:.14em">CAMERA SCAN</div></div><p class="muted" style="text-align:center;font-size:12px">Point the camera at a MASA QR code.</p><div class="modal-actions"><button onclick="showToast('Gallery picker requires app permission')">Gallery</button><button class="gold" onclick="receiveScreen()">My QR</button></div>`)}
function activityScreen(){openModal(`<div class="modal-head"><h3>Activity</h3><button class="close" onclick="closeModal()">×</button></div><div class="activity-list"><div class="activity-row"><div class="activity-icon received">↓</div><div><b>Received</b><span>From MASA1...8KQ2 · 2m ago</span></div><strong class="positive">+120 MASA</strong></div><div class="activity-row"><div class="activity-icon sent">↑</div><div><b>Sent</b><span>To MASA1...9P7D · 1h ago</span></div><strong class="negative">-50 MASA</strong></div><div class="activity-row"><div class="activity-icon mining">⛏</div><div><b>Mining Reward</b><span>Network contribution · 5h ago</span></div><strong class="positive">+8 MASA</strong></div></div>`)}
function settingsScreen(){openModal(`<div class="modal-head"><h3>Settings</h3><button class="close" onclick="closeModal()">×</button></div><div class="ecosystem-card"><div class="eco-icon">🔐</div><div><b>Security</b><span>Biometric · PIN · Recovery Phrase</span></div></div><div class="ecosystem-card"><div class="eco-icon">●</div><div><b>Network</b><span>MASA Mainnet</span></div></div><div class="ecosystem-card"><div class="eco-icon">⌁</div><div><b>Connected Apps</b><span>DEX · Miner · MSR</span></div></div>`)}
function assetsScreen(){openModal(`<div class="modal-head"><h3>My Assets</h3><button class="close" onclick="closeModal()">×</button></div><div class="asset-row featured"><img src="assets/masa-logo.png" alt="MASA"><div><b>MASA</b><span>MASA Mainnet</span></div><div class="asset-value"><b>12,482.51</b></div></div><div class="asset-row"><div class="asset-badge msr">M</div><div><b>MSR</b><span>Market Intelligence</span></div><div class="asset-value"><b>320.00</b></div></div>`)}
function route(screen){if(screen==='send')sendScreen();if(screen==='receive')receiveScreen();if(screen==='scan')scanScreen();if(screen==='activity')activityScreen();if(screen==='settings')settingsScreen();if(screen==='assets')assetsScreen()}
document.querySelectorAll('[data-screen]').forEach(el=>el.addEventListener('click',()=>route(el.dataset.screen)));
document.getElementById('notifyBtn').onclick=()=>showToast('No new notifications');document.getElementById('menuBtn').onclick=()=>settingsScreen();
